"""2026-01-17-12_04

Revision ID: f713818a02ec
Revises: 8a00d9257281
Create Date: 2026-01-17 12:04:54.056852

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f713818a02ec"
down_revision = "8a00d9257281"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "join_requests",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "DECLINED", name="joinrequeststatus"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_join_requests_requested_by"),
        "join_requests",
        ["requested_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_join_requests_status"), "join_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_join_requests_team_id"), "join_requests", ["team_id"], unique=False
    )
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("OWNER", "ADMIN", "MEMBER", name="teamrole"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "user_id", name="uq_team_members_team_user"),
    )
    op.create_index(
        op.f("ix_team_members_role"), "team_members", ["role"], unique=False
    )
    op.create_index(
        op.f("ix_team_members_team_id"), "team_members", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_members_user_id"), "team_members", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_members_user_id"), table_name="team_members")
    op.drop_index(op.f("ix_team_members_team_id"), table_name="team_members")
    op.drop_index(op.f("ix_team_members_role"), table_name="team_members")
    op.drop_table("team_members")
    op.drop_index(op.f("ix_join_requests_team_id"), table_name="join_requests")
    op.drop_index(op.f("ix_join_requests_status"), table_name="join_requests")
    op.drop_index(op.f("ix_join_requests_requested_by"), table_name="join_requests")
    op.drop_table("join_requests")
    # ### end Alembic commands ###
