"""2026-01-17-18_04

Revision ID: 498f18af3816
Revises: ab53ff3f91ae
Create Date: 2026-01-17 18:04:49.210093

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "498f18af3816"
down_revision = "ab53ff3f91ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up duplicate PENDING requests before creating the constraint
    # Keep only the most recent PENDING request for each (team_id, requested_by) pair
    op.execute(
        """
        DELETE FROM join_requests
        WHERE id IN (
            SELECT id
            FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY team_id, requested_by
                           ORDER BY created_at DESC
                       ) as rn
                FROM join_requests
                WHERE status = 'PENDING'
            ) t
            WHERE t.rn > 1
        )
    """
    )

    # Create a partial unique index that only enforces uniqueness for PENDING status
    # This allows historical duplicates (APPROVED/DECLINED) but prevents concurrent PENDING requests
    op.execute(
        """
        CREATE UNIQUE INDEX uq_join_request_team_user_pending
        ON join_requests (team_id, requested_by)
        WHERE status = 'PENDING'
    """
    )

    op.alter_column(
        "teams",
        "status",
        existing_type=postgresql.ENUM("ACTIVE", "DELETED", name="teamstatus"),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teams",
        "status",
        existing_type=postgresql.ENUM("ACTIVE", "DELETED", name="teamstatus"),
        server_default=sa.text("'ACTIVE'::teamstatus"),
        existing_nullable=False,
    )
    op.execute("DROP INDEX IF EXISTS uq_join_request_team_user_pending")
    # ### end Alembic commands ###
