"""Upgrade fields in user table

Revision ID: a0074a1d96ee
Revises: 7fa41ff5d127
Create Date: 2025-11-14 10:24:04.376915

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0074a1d96ee"
down_revision = "7fa41ff5d127"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Step 1: Add new columns as nullable first
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.add_column("users", sa.Column("country_code", sa.String(), nullable=True))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))

    # Step 2: Populate the new columns with data from existing rows
    # Combine first_name and last_name into name
    op.execute(
        """
        UPDATE users 
        SET name = CONCAT(first_name, ' ', last_name)
        WHERE name IS NULL
    """
    )

    # Generate username from email (take part before @)
    op.execute(
        """
        UPDATE users 
        SET username = SPLIT_PART(email, '@', 1)
        WHERE username IS NULL
    """
    )

    # Set default values for country_code and is_active
    op.execute(
        """
        UPDATE users 
        SET country_code = 'US'
        WHERE country_code IS NULL
    """
    )

    op.execute(
        """
        UPDATE users 
        SET is_active = TRUE
        WHERE is_active IS NULL
    """
    )

    # Step 3: Now make the columns NOT NULL
    op.alter_column("users", "name", nullable=False)
    op.alter_column("users", "username", nullable=False)
    op.alter_column("users", "country_code", nullable=False)
    op.alter_column("users", "is_active", nullable=False)

    # Step 4: Drop old columns and indexes
    op.drop_index(op.f("ix_users_first_name"), table_name="users")
    op.drop_index(op.f("ix_users_last_name"), table_name="users")
    op.create_index(
        op.f("ix_users_country_code"), "users", ["country_code"], unique=False
    )
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_country_code"), table_name="users")
    op.create_index(op.f("ix_users_last_name"), "users", ["last_name"], unique=False)
    op.create_index(op.f("ix_users_first_name"), "users", ["first_name"], unique=False)
    op.drop_column("users", "is_active")
    op.drop_column("users", "country_code")
    op.drop_column("users", "username")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
